language: cpp
os: osx
env: OSX=10.12
osx_image: xcode8.3

before_install:
  - brew update
  - brew unlink pkg-config || true
  - brew unlink cmake || true
  - brew install pkg-config
  - brew link pkg-config
  - brew install gettext jack docbook-xsl cmake fftw wavpack
  - brew install -v --HEAD wxmac
  - brew link gettext --force

script:
  - cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS=-g -DCMAKE_C_FLAGS=-g -DDOCBOOK_DIR=/usr/local/opt/docbook-xsl/docbook-xsl -DVERSION_REVISION=`git log |grep git-svn-id  |head -1 |sed -e 's/.*@\([0-9]*\) .*/\1/g'` .
  - make -k package VERBOSE=1
  - sed -i old -e "s/0.3.1.X/0.3.1.`git log |grep git-svn-id  |head -1 |sed -e 's/.*@\([0-9]*\) .*/\1/g'`/g" obs/bintray.json

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: bintray
  skip_cleanup: true
  file: obs/bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    all_branches: true
