/*
 * Copyright (c) 2003, 2007-11 Matteo Frigo
 * Copyright (c) 2003, 2007-11 Massachusetts Institute of Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/* This file was automatically generated --- DO NOT EDIT */
/* Generated on Sat Apr 28 10:59:09 EDT 2012 */

#include "codelet-dft.h"

#ifdef HAVE_FMA

/* Generated by: ../../../genfft/gen_twiddle.native -fma -reorder-insns -schedule-for-pipeline -compact -variables 4 -pipeline-latency 4 -n 6 -name t1_6 -include t.h */

/*
 * This function contains 46 FP additions, 32 FP multiplications,
 * (or, 24 additions, 10 multiplications, 22 fused multiply/add),
 * 47 stack variables, 2 constants, and 24 memory accesses
 */
#include "t.h"

static void t1_6(R *ri, R *ii, const R *W, stride rs, INT mb, INT me, INT ms)
{
     DK(KP866025403, +0.866025403784438646763723170752936183471402627);
     DK(KP500000000, +0.500000000000000000000000000000000000000000000);
     {
	  INT m;
	  for (m = mb, W = W + (mb * 10); m < me; m = m + 1, ri = ri + ms, ii = ii + ms, W = W + 10, MAKE_VOLATILE_STRIDE(rs)) {
	       E TY, TU, T10, TZ;
	       {
		    E T1, TX, TW, T7, Tn, Tq, TJ, TR, TB, Tl, To, TK, Tt, Tw, Ts;
		    E Tp, Tv;
		    T1 = ri[0];
		    TX = ii[0];
		    {
			 E T3, T6, T2, T5;
			 T3 = ri[WS(rs, 3)];
			 T6 = ii[WS(rs, 3)];
			 T2 = W[4];
			 T5 = W[5];
			 {
			      E Ta, Td, Tg, TF, Tb, Tj, Tf, Tc, Ti, TV, T4, T9;
			      Ta = ri[WS(rs, 2)];
			      Td = ii[WS(rs, 2)];
			      TV = T2 * T6;
			      T4 = T2 * T3;
			      T9 = W[2];
			      Tg = ri[WS(rs, 5)];
			      TW = FNMS(T5, T3, TV);
			      T7 = FMA(T5, T6, T4);
			      TF = T9 * Td;
			      Tb = T9 * Ta;
			      Tj = ii[WS(rs, 5)];
			      Tf = W[8];
			      Tc = W[3];
			      Ti = W[9];
			      {
				   E TG, Te, TI, Tk, TH, Th, Tm;
				   Tn = ri[WS(rs, 4)];
				   TH = Tf * Tj;
				   Th = Tf * Tg;
				   TG = FNMS(Tc, Ta, TF);
				   Te = FMA(Tc, Td, Tb);
				   TI = FNMS(Ti, Tg, TH);
				   Tk = FMA(Ti, Tj, Th);
				   Tq = ii[WS(rs, 4)];
				   Tm = W[6];
				   TJ = TG - TI;
				   TR = TG + TI;
				   TB = Te + Tk;
				   Tl = Te - Tk;
				   To = Tm * Tn;
				   TK = Tm * Tq;
			      }
			      Tt = ri[WS(rs, 1)];
			      Tw = ii[WS(rs, 1)];
			      Ts = W[0];
			      Tp = W[7];
			      Tv = W[1];
			 }
		    }
		    {
			 E TA, T8, TL, Tr, TN, Tx, T11, TM, Tu;
			 TA = T1 + T7;
			 T8 = T1 - T7;
			 TM = Ts * Tw;
			 Tu = Ts * Tt;
			 TL = FNMS(Tp, Tn, TK);
			 Tr = FMA(Tp, Tq, To);
			 TN = FNMS(Tv, Tt, TM);
			 Tx = FMA(Tv, Tw, Tu);
			 T11 = TX - TW;
			 TY = TW + TX;
			 {
			      E TP, TT, TD, TE, TQ, Tz, T14, T13;
			      {
				   E TO, TS, TC, Ty, T12;
				   TO = TL - TN;
				   TS = TL + TN;
				   TC = Tr + Tx;
				   Ty = Tr - Tx;
				   T12 = TJ + TO;
				   TP = TJ - TO;
				   TT = TR - TS;
				   TU = TR + TS;
				   Tz = Tl + Ty;
				   T14 = Ty - Tl;
				   ii[WS(rs, 3)] = T12 + T11;
				   T13 = FNMS(KP500000000, T12, T11);
				   T10 = TC - TB;
				   TD = TB + TC;
			      }
			      ri[WS(rs, 3)] = T8 + Tz;
			      TE = FNMS(KP500000000, Tz, T8);
			      ii[WS(rs, 5)] = FNMS(KP866025403, T14, T13);
			      ii[WS(rs, 1)] = FMA(KP866025403, T14, T13);
			      TQ = FNMS(KP500000000, TD, TA);
			      ri[WS(rs, 5)] = FNMS(KP866025403, TP, TE);
			      ri[WS(rs, 1)] = FMA(KP866025403, TP, TE);
			      ri[0] = TA + TD;
			      ri[WS(rs, 4)] = FMA(KP866025403, TT, TQ);
			      ri[WS(rs, 2)] = FNMS(KP866025403, TT, TQ);
			 }
		    }
	       }
	       ii[0] = TU + TY;
	       TZ = FNMS(KP500000000, TU, TY);
	       ii[WS(rs, 2)] = FNMS(KP866025403, T10, TZ);
	       ii[WS(rs, 4)] = FMA(KP866025403, T10, TZ);
	  }
     }
}

static const tw_instr twinstr[] = {
     {TW_FULL, 0, 6},
     {TW_NEXT, 1, 0}
};

static const ct_desc desc = { 6, "t1_6", twinstr, &GENUS, {24, 10, 22, 0}, 0, 0, 0 };

void X(codelet_t1_6) (planner *p) {
     X(kdft_dit_register) (p, t1_6, &desc);
}
#else				/* HAVE_FMA */

/* Generated by: ../../../genfft/gen_twiddle.native -compact -variables 4 -pipeline-latency 4 -n 6 -name t1_6 -include t.h */

/*
 * This function contains 46 FP additions, 28 FP multiplications,
 * (or, 32 additions, 14 multiplications, 14 fused multiply/add),
 * 23 stack variables, 2 constants, and 24 memory accesses
 */
#include "t.h"

static void t1_6(R *ri, R *ii, const R *W, stride rs, INT mb, INT me, INT ms)
{
     DK(KP500000000, +0.500000000000000000000000000000000000000000000);
     DK(KP866025403, +0.866025403784438646763723170752936183471402627);
     {
	  INT m;
	  for (m = mb, W = W + (mb * 10); m < me; m = m + 1, ri = ri + ms, ii = ii + ms, W = W + 10, MAKE_VOLATILE_STRIDE(rs)) {
	       E T7, TS, Tv, TO, Tt, TJ, Tx, TF, Ti, TI, Tw, TC;
	       {
		    E T1, TN, T6, TM;
		    T1 = ri[0];
		    TN = ii[0];
		    {
			 E T3, T5, T2, T4;
			 T3 = ri[WS(rs, 3)];
			 T5 = ii[WS(rs, 3)];
			 T2 = W[4];
			 T4 = W[5];
			 T6 = FMA(T2, T3, T4 * T5);
			 TM = FNMS(T4, T3, T2 * T5);
		    }
		    T7 = T1 - T6;
		    TS = TN - TM;
		    Tv = T1 + T6;
		    TO = TM + TN;
	       }
	       {
		    E Tn, TD, Ts, TE;
		    {
			 E Tk, Tm, Tj, Tl;
			 Tk = ri[WS(rs, 4)];
			 Tm = ii[WS(rs, 4)];
			 Tj = W[6];
			 Tl = W[7];
			 Tn = FMA(Tj, Tk, Tl * Tm);
			 TD = FNMS(Tl, Tk, Tj * Tm);
		    }
		    {
			 E Tp, Tr, To, Tq;
			 Tp = ri[WS(rs, 1)];
			 Tr = ii[WS(rs, 1)];
			 To = W[0];
			 Tq = W[1];
			 Ts = FMA(To, Tp, Tq * Tr);
			 TE = FNMS(Tq, Tp, To * Tr);
		    }
		    Tt = Tn - Ts;
		    TJ = TD + TE;
		    Tx = Tn + Ts;
		    TF = TD - TE;
	       }
	       {
		    E Tc, TA, Th, TB;
		    {
			 E T9, Tb, T8, Ta;
			 T9 = ri[WS(rs, 2)];
			 Tb = ii[WS(rs, 2)];
			 T8 = W[2];
			 Ta = W[3];
			 Tc = FMA(T8, T9, Ta * Tb);
			 TA = FNMS(Ta, T9, T8 * Tb);
		    }
		    {
			 E Te, Tg, Td, Tf;
			 Te = ri[WS(rs, 5)];
			 Tg = ii[WS(rs, 5)];
			 Td = W[8];
			 Tf = W[9];
			 Th = FMA(Td, Te, Tf * Tg);
			 TB = FNMS(Tf, Te, Td * Tg);
		    }
		    Ti = Tc - Th;
		    TI = TA + TB;
		    Tw = Tc + Th;
		    TC = TA - TB;
	       }
	       {
		    E TG, Tu, Tz, TR, TT, TU;
		    TG = KP866025403 * (TC - TF);
		    Tu = Ti + Tt;
		    Tz = FNMS(KP500000000, Tu, T7);
		    ri[WS(rs, 3)] = T7 + Tu;
		    ri[WS(rs, 1)] = Tz + TG;
		    ri[WS(rs, 5)] = Tz - TG;
		    TR = KP866025403 * (Tt - Ti);
		    TT = TC + TF;
		    TU = FNMS(KP500000000, TT, TS);
		    ii[WS(rs, 1)] = TR + TU;
		    ii[WS(rs, 3)] = TT + TS;
		    ii[WS(rs, 5)] = TU - TR;
	       }
	       {
		    E TK, Ty, TH, TQ, TL, TP;
		    TK = KP866025403 * (TI - TJ);
		    Ty = Tw + Tx;
		    TH = FNMS(KP500000000, Ty, Tv);
		    ri[0] = Tv + Ty;
		    ri[WS(rs, 4)] = TH + TK;
		    ri[WS(rs, 2)] = TH - TK;
		    TQ = KP866025403 * (Tx - Tw);
		    TL = TI + TJ;
		    TP = FNMS(KP500000000, TL, TO);
		    ii[0] = TL + TO;
		    ii[WS(rs, 4)] = TQ + TP;
		    ii[WS(rs, 2)] = TP - TQ;
	       }
	  }
     }
}

static const tw_instr twinstr[] = {
     {TW_FULL, 0, 6},
     {TW_NEXT, 1, 0}
};

static const ct_desc desc = { 6, "t1_6", twinstr, &GENUS, {32, 14, 14, 0}, 0, 0, 0 };

void X(codelet_t1_6) (planner *p) {
     X(kdft_dit_register) (p, t1_6, &desc);
}
#endif				/* HAVE_FMA */
