#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    PIPEWIRE_JACK_CONF=/etc/ld.so.conf.d/grandorgue-pipewire-jack.conf
    if dpkg -s pipewire-jack >/dev/null 2>&1; then
        MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH 2>/dev/null || true)
        if [ -n "$MULTIARCH" ]; then
            JACK_PATH="/usr/lib/$MULTIARCH/pipewire-0.3/jack"
            if [ -d "$JACK_PATH" ]; then
                echo "$JACK_PATH" > "$PIPEWIRE_JACK_CONF"
            fi
        fi
    fi
    ldconfig
fi
