/*
 * Copyright 2006 Milan Digital Audio LLC
 * Copyright 2009-2024 GrandOrgue contributors (see AUTHORS)
 * License GPL-2.0 or later
 * (https://www.gnu.org/licenses/old-licenses/gpl-2.0.html).
 */

#ifndef GOMIDIRECEIVERMESSAGETYPE_H
#define GOMIDIRECEIVERMESSAGETYPE_H

enum GOMidiReceiverMessageType {
  MIDI_M_NONE,
  MIDI_M_NOTE,
  MIDI_M_CTRL_CHANGE,
  MIDI_M_PGM_CHANGE,
  MIDI_M_PGM_RANGE,
  MIDI_M_SYSEX_JOHANNUS_9,
  MIDI_M_SYSEX_JOHANNUS_11,
  MIDI_M_SYSEX_VISCOUNT,
  MIDI_M_SYSEX_VISCOUNT_TOGGLE,
  MIDI_M_SYSEX_RODGERS_STOP_CHANGE,
  MIDI_M_SYSEX_AHLBORN_GALANTI,
  MIDI_M_SYSEX_AHLBORN_GALANTI_TOGGLE,
  MIDI_M_CTRL_BIT,
  MIDI_M_CTRL_CHANGE_FIXED,
  MIDI_M_RPN,
  MIDI_M_NRPN,
  MIDI_M_RPN_RANGE,
  MIDI_M_NRPN_RANGE,
  MIDI_M_NOTE_ON,
  MIDI_M_NOTE_OFF,
  MIDI_M_NOTE_ON_OFF,
  MIDI_M_NOTE_FIXED_ON,
  MIDI_M_NOTE_FIXED_OFF,
  MIDI_M_CTRL_CHANGE_ON,
  MIDI_M_CTRL_CHANGE_OFF,
  MIDI_M_CTRL_CHANGE_ON_OFF,
  MIDI_M_CTRL_CHANGE_FIXED_ON,
  MIDI_M_CTRL_CHANGE_FIXED_OFF,
  MIDI_M_CTRL_CHANGE_FIXED_ON_OFF,
  MIDI_M_RPN_ON,
  MIDI_M_RPN_OFF,
  MIDI_M_RPN_ON_OFF,
  MIDI_M_NRPN_ON,
  MIDI_M_NRPN_OFF,
  MIDI_M_NRPN_ON_OFF,
  MIDI_M_NOTE_NO_VELOCITY,
  MIDI_M_NOTE_SHORT_OCTAVE,
  MIDI_M_NOTE_NORMAL,
};

#endif /* GOMIDIRECEIVERMESSAGETYPE_H */
